openapi: 3.0.1
info:
  title: kotohiro
  description: ''
  version: 1.0.0
tags:
  - name: vote
  - name: opinion
  - name: talk_session
  - name: user
  - name: auth
  - name: test
paths:
  /talksessions/{talkSessionID}/opinions/{opinionID}/votes:
    post:
      summary: 意思表明API
      deprecated: false
      description: ''
      operationId: vote
      tags:
        - vote
      parameters:
        - name: talkSessionID
          in: path
          description: セッションのID
          required: true
          schema:
            type: string
        - name: opinionID
          in: path
          description: 意見のID
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                voteStatus:
                  type: string
                  enum:
                    - agree
                    - disagree
                    - pass
                  example: ''
                  nullable: true
              required:
                - voteStatus
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items: &ref_0
                  $ref: '#/components/schemas/opinion'
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: Vote
  /talksessions/{talkSessionID}/swipe_opinions:
    get:
      summary: スワイプ用のエンドポイント
      deprecated: false
      description: セッションの中からまだ投票していない意見をランダムに取得する
      operationId: swipe_opinions
      tags:
        - opinion
      parameters:
        - name: talkSessionID
          in: path
          description: ''
          required: true
          schema:
            type: string
        - name: limit
          in: query
          description: ''
          required: false
          schema:
            type: integer
            default: 10
            nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    opinion: *ref_0
                    user: &ref_1
                      $ref: '#/components/schemas/user'
                      description: 作成ユーザー
                    replyCount:
                      type: integer
                  required:
                    - opinion
                    - user
                    - replyCount
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: Opinion
  /talksessions/{talkSessionID}/opinions:
    post:
      summary: セッションに対して意見投稿
      deprecated: false
      description: parentOpinionIDがなければルートの意見として投稿される
      operationId: postOpinionPost
      tags:
        - opinion
      parameters:
        - name: talkSessionID
          in: path
          description: ''
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                parentOpinionID:
                  type: string
                  example: ''
                  nullable: true
                title:
                  type: string
                  example: ''
                  nullable: true
                opinionContent:
                  type: string
                  maxLength: 140
                  example: ''
                referenceURL:
                  type: string
                  format: url
                  example: ''
                  nullable: true
                picture:
                  type: string
                  format: binary
                  description: 参考画像。4MiBまで
                  example: ''
              required:
                - opinionContent
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: Opinion
    get:
      summary: セッションに対する意見一覧
      deprecated: false
      description: ''
      operationId: getOpinionsForTalkSession
      tags:
        - opinion
      parameters:
        - name: talkSessionID
          in: path
          description: ''
          required: true
          schema:
            type: string
        - name: sort
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - latest
              - mostReply
              - oldest
            x-apidog:
              enumDescriptions:
                latest: ''
                mostReply: ''
                oldest: ''
            nullable: true
        - name: limit
          in: query
          description: ''
          required: false
          example: 10
          schema:
            type: integer
            nullable: true
        - name: offset
          in: query
          description: ''
          required: false
          example: 0
          schema:
            type: integer
            nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  opinions:
                    type: array
                    items:
                      type: object
                      properties:
                        opinion: *ref_0
                        user: *ref_1
                        replyCount:
                          type: integer
                        myVoteType: &ref_4
                          $ref: '#/components/schemas/voteType'
                          description: 意見投稿主の意見。ルート意見の場合はここには何も入らない
                      required:
                        - opinion
                        - user
                        - replyCount
                        - myVoteType
                  pagination:
                    type: object
                    properties:
                      totalCount:
                        type: integer
                    required:
                      - totalCount
                required:
                  - opinions
                  - pagination
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: Opinion
  /talksessions/{talkSessionID}/opinions/{opinionID}:
    get:
      summary: 意見の詳細
      deprecated: false
      description: ''
      operationId: getOpinionDetail
      tags:
        - opinion
      parameters:
        - name: talkSessionID
          in: path
          description: ''
          required: true
          schema:
            type: string
        - name: opinionID
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  opinion: *ref_0
                  user: *ref_1
                required:
                  - opinion
                  - user
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: Opinion
  /talksessions/{talkSessionId}:
    get:
      summary: トークセッションの詳細
      deprecated: false
      description: ''
      operationId: getTalkSessionDetail
      tags:
        - talk_session
      parameters:
        - name: talkSessionId
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema: &ref_2
                $ref: '#/components/schemas/talkSession'
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: TalkSession
  /talksessions:
    get:
      summary: セッション一覧
      deprecated: false
      description: ''
      operationId: getTalkSessionList
      tags:
        - talk_session
      parameters:
        - name: limit
          in: query
          description: 1ページあたりの要素数
          required: false
          example: 10
          schema:
            type: integer
            nullable: true
        - name: offset
          in: query
          description: どの要素から始めるか
          required: false
          example: 0
          schema:
            type: integer
            nullable: true
        - name: theme
          in: query
          description: ''
          required: false
          schema:
            type: string
            nullable: true
        - name: status
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - open
              - finished
            default: open
            x-apidog-enum:
              - name: ''
                value: open
                description: 開催中
              - name: ''
                value: finished
                description: 終了済み
            nullable: true
        - name: sortKey
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - latest
              - oldest
              - mostReplies
            x-apidog:
              enumDescriptions:
                latest: ''
                oldest: ''
                mostReplies: ''
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  talkSessions:
                    type: array
                    items:
                      type: object
                      properties:
                        talkSession: *ref_2
                        opinionCount:
                          type: integer
                      required:
                        - talkSession
                        - opinionCount
                  pagination: &ref_5
                    $ref: '#/components/schemas/offsetPagination'
                required:
                  - talkSessions
                  - pagination
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: TalkSession
    post:
      summary: セッション作成
      deprecated: false
      description: ''
      operationId: createTalkSession
      tags:
        - talk_session
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                theme:
                  type: string
                  maxLength: 50
                  minLength: 5
                  example: オブジェクト指向は悪
                scheduledEndTime:
                  type: string
                  format: date-time
                  example: '2024-12-17T03:24:00Z'
                latitude:
                  type: number
                  description: 緯度
                  example: 0
                  nullable: true
                longitude:
                  type: number
                  description: 経度
                  example: 0
                  nullable: true
                city:
                  type: string
                  description: 市区町村
                  example: ''
                  nullable: true
                prefecture:
                  type: string
                  description: 都道府県
                  example: ''
                  nullable: true
              required:
                - theme
                - scheduledEndTime
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: トークセッションID
                  theme:
                    type: string
                    description: テーマ
                  owner: *ref_1
                  createdAt:
                    type: string
                    description: 作成日時
                  scheduledEndTime:
                    type: string
                    description: 終了予定日時
                  location:
                    anyOf:
                      - &ref_6
                        $ref: '#/components/schemas/location'
                      - type: 'null'
                    description: 位置情報
                  city:
                    type: string
                    description: 市区町村
                    nullable: true
                  prefecture:
                    type: string
                    description: 都道府県
                    nullable: true
                required:
                  - id
                  - theme
                  - owner
                  - createdAt
                  - scheduledEndTime
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: TalkSession
  /talksessions/{talkSessionId}/analysis:
    get:
      summary: 分析結果一覧
      deprecated: false
      description: ''
      operationId: talkSessionAnalysis
      tags:
        - talk_session
      parameters:
        - name: talkSessionId
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  myPosition: &ref_3
                    $ref: '#/components/schemas/userGroupPosition'
                  positions:
                    type: array
                    items: *ref_3
                  groupOpinions:
                    type: array
                    items:
                      type: object
                      properties:
                        groupName:
                          type: string
                        groupId:
                          type: integer
                        opinions:
                          type: array
                          items:
                            type: object
                            properties:
                              opinion: *ref_0
                              user: *ref_1
                              agreeCount:
                                type: integer
                              disagreeCount:
                                type: integer
                              passCount:
                                type: integer
                            required:
                              - opinion
                              - user
                              - agreeCount
                              - disagreeCount
                              - passCount
                      required:
                        - groupName
                        - opinions
                        - groupId
                required:
                  - positions
                  - groupOpinions
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: TalkSession
  /talksessions/{talkSessionId}/report:
    get:
      summary: セッションレポートを返す
      deprecated: false
      description: ''
      operationId: getTalkSessionReport
      tags:
        - talk_session
      parameters:
        - name: talkSessionId
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  report:
                    type: string
                required:
                  - report
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: TalkSession
  /talksessions/{talkSessionID}/opinions/{opinionID}/replies:
    get:
      summary: 意見に対するリプライ意見一覧
      deprecated: false
      description: ''
      operationId: opinionComments
      tags:
        - opinion
      parameters:
        - name: talkSessionID
          in: path
          description: ''
          required: true
          schema:
            type: string
        - name: opinionID
          in: path
          description: 親意見のID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  rootOpinion:
                    type: object
                    properties:
                      user: *ref_1
                      myVoteType: *ref_4
                      opinion: *ref_0
                    required:
                      - user
                      - opinion
                      - myVoteType
                  opinions:
                    type: array
                    items:
                      type: object
                      properties:
                        opinion: *ref_0
                        user: *ref_1
                        myVoteType:
                          anyOf:
                            - *ref_4
                            - type: 'null'
                      required:
                        - opinion
                        - user
                required:
                  - rootOpinion
                  - opinions
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: Opinion
  /talksessions/{talkSessionID}/opinions/{opinionID}/replies2:
    get:
      summary: 意見に対するリプライ意見一覧 Copy
      deprecated: false
      description: ''
      operationId: opinionComments2
      tags:
        - opinion
      parameters:
        - name: talkSessionID
          in: path
          description: ''
          required: true
          schema:
            type: string
        - name: opinionID
          in: path
          description: 親意見のID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  rootOpinion:
                    type: object
                    properties:
                      user: *ref_1
                      opinion: *ref_0
                    required:
                      - user
                      - opinion
                  replyOpinions:
                    type: array
                    items:
                      type: object
                      properties:
                        opinion: *ref_0
                        user: *ref_1
                        myVoteType:
                          anyOf:
                            - *ref_4
                            - type: 'null'
                      required:
                        - opinion
                        - user
                  parentOpinions:
                    type: array
                    items:
                      type: object
                      properties:
                        opinion: *ref_0
                        user: *ref_1
                        myVoteType: *ref_4
                        level:
                          type: integer
                      required:
                        - opinion
                        - user
                        - myVoteType
                        - level
                required:
                  - rootOpinion
                  - replyOpinions
                  - parentOpinions
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: Opinion
  /user:
    put:
      summary: ユーザー情報の変更
      deprecated: false
      description: ''
      operationId: editUserProfile
      tags:
        - user
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                  description: ユーザー名
                  example: ''
                  nullable: true
                icon:
                  type: string
                  format: binary
                  description: ユーザーアイコン
                  example: ''
                deleteIcon:
                  type: boolean
                  default: false
                  example: 'false'
                  nullable: true
                yearOfBirth:
                  type: integer
                  description: 生まれ年
                  example: 0
                  nullable: true
                gender:
                  type: string
                  enum:
                    - 男性
                    - 女性
                    - その他
                    - 回答しない
                  description: 性別
                  example: ''
                  nullable: true
                city:
                  type: string
                  description: 市区町村
                  example: ''
                  nullable: true
                occupation:
                  type: string
                  enum:
                    - 正社員
                    - 契約社員
                    - 公務員
                    - 自営業
                    - 会社役員
                    - パート・アルバイト
                    - 家事従事者
                    - 学生
                    - 無職
                    - その他
                    - 回答しない
                  description: 職業
                  example: ''
                  nullable: true
                householdSize:
                  type: integer
                  description: 世帯人数
                  example: 0
                  nullable: true
                prefecture:
                  type: string
                  description: 都道府県
                  example: ''
                  nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  displayID:
                    type: string
                    pattern: ^[A-Za-z0-9]$
                    examples:
                      - userid
                    minLength: 3
                    maxLength: 25
                  displayName:
                    type: string
                  iconURL:
                    type: string
                    nullable: true
                required:
                  - displayID
                  - displayName
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: user
    get:
      summary: ユーザー情報の取得
      deprecated: false
      description: ''
      operationId: get_user_info
      tags:
        - user
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  user: *ref_1
                  demographics:
                    $ref: '#/components/schemas/userDemographics'
                required:
                  - user
                  - demographics
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: User
    post:
      summary: ユーザー作成
      deprecated: false
      description: ''
      operationId: registerUser
      tags:
        - user
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                displayName:
                  type: string
                  description: ユーザー名。日本語なども設定可能。
                  example: hogesge
                displayID:
                  type: string
                  description: ユーザーID。プロフィールのパスなどで使用される。DBのIDとは別。
                  example: suge-
                icon:
                  format: binary
                  type: string
                  description: ユーザーアイコン
                  example: ''
                yearOfBirth:
                  type: integer
                  default: 0
                  description: 生まれ年
                  example: 0
                  nullable: true
                gender:
                  type: string
                  enum:
                    - 男性
                    - 女性
                    - その他
                    - 回答しない
                  default: preferNotToSay
                  description: 性別
                  example: ''
                  nullable: true
                prefecture:
                  description: 都道府県
                  example: ''
                  type: string
                city:
                  type: string
                  description: 市区町村
                  example: ''
                  nullable: true
                occupation:
                  type: string
                  enum:
                    - 正社員
                    - 契約社員
                    - 公務員
                    - 自営業
                    - 会社役員
                    - パート・アルバイト
                    - 家事従事者
                    - 学生
                    - 無職
                    - その他
                    - 回答しない
                  default: 無回答
                  description: ユーザーの職業
                  example: ''
                  nullable: true
                householdSize:
                  type: integer
                  minimum: 0
                  description: 世帯人数
                  example: 0
                  nullable: true
              required:
                - displayName
                - displayID
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  displayID:
                    type: string
                    pattern: ^[A-Za-z0-9]$
                    examples:
                      - userid
                    minLength: 3
                    maxLength: 25
                  displayName:
                    type: string
                  iconURL:
                    type: string
                    nullable: true
                required:
                  - displayID
                  - displayName
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: user
  /opinions/histories:
    get:
      summary: 今までに投稿した異見
      deprecated: false
      description: ''
      operationId: opinionsHistory
      tags:
        - user
      parameters:
        - name: sort
          in: query
          description: ソートきー
          required: false
          schema:
            type: string
            enum:
              - latest
              - mostReply
              - oldest
            x-apidog:
              enumDescriptions:
                latest: 最新
                mostReply: もっともリプライされた
                oldest: 最古
            nullable: true
        - name: limit
          in: query
          description: ''
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: ''
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  opinions:
                    type: array
                    items:
                      type: object
                      properties:
                        user: *ref_1
                        opinion: *ref_0
                        replyCount:
                          type: integer
                      required:
                        - user
                        - opinion
                        - replyCount
                  pagination:
                    type: object
                    properties:
                      totalCount:
                        type: integer
                    required:
                      - totalCount
                required:
                  - opinions
                  - pagination
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: User
  /talksessions/histories:
    get:
      summary: リアクション済みのセッション一覧
      deprecated: false
      description: ''
      operationId: sessionsHistory
      tags:
        - user
      parameters:
        - name: limit
          in: query
          description: ''
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          description: ''
          required: false
          schema:
            type: integer
        - name: theme
          in: query
          description: 'テーマ '
          required: false
          schema:
            type: string
            nullable: true
        - name: status
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - open
              - finished
            x-apidog:
              enumDescriptions:
                open: ''
                finished: ''
            nullable: true
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  pagination: *ref_5
                  talkSessions:
                    type: array
                    items:
                      type: object
                      properties:
                        opinionCount:
                          type: integer
                        talkSession: *ref_2
                      required:
                        - opinionCount
                        - talkSession
                required:
                  - pagination
                  - talkSessions
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: User
  /auth/token/info:
    get:
      summary: JWTの内容を返してくれる
      deprecated: false
      description: ''
      operationId: oauth_token_info
      tags:
        - auth
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  aud:
                    type: string
                    description: Audience
                  exp:
                    type: string
                    description: 有効期限
                  iat:
                    type: string
                    description: 発行日時
                  iss:
                    type: string
                    description: 発行者
                  sub:
                    type: string
                    description: ユーザID
                  jti:
                    type: string
                    description: JWT ID
                  displayId:
                    type: string
                    description: ユーザーID
                  displayName:
                    type: string
                    description: ユーザー名
                  iconURL:
                    type: string
                    description: アイコンURL
                  isVerify:
                    type: boolean
                    description: ユーザ登録済みか
                required:
                  - aud
                  - exp
                  - iat
                  - iss
                  - sub
                  - jti
                  - isVerify
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                required:
                  - code
                  - message
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security:
        - apikey-header-SessionId: []
      x-ogen-operation-group: Auth
  /test:
    get:
      summary: OpenAPIテスト用
      deprecated: false
      description: ''
      operationId: test
      tags:
        - user
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  optInt:
                    type: integer
                    nullable: true
                  optNilInt:
                    type: integer
                  optNilBool:
                    type: boolean
                    nullable: true
                  optBool:
                    type: boolean
                  optUrl:
                    type: string
                    format: uri
                  optNilUrl:
                    type: string
                    format: url
                    nullable: true
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: test
  /test/dummy:
    post:
      summary: mudai
      deprecated: false
      description: ''
      operationId: dummiInit
      tags:
        - test
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
        '400':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
        '500':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                '1':
                  summary: internal
                  value:
                    code: GENERAL-000
                    message: INTERNAL SERVER ERROR.
          headers: {}
      security: []
      x-ogen-operation-group: Test
components:
  schemas:
    talkSession:
      type: object
      properties:
        id:
          type: string
          description: トークセッションID
        theme:
          type: string
          description: テーマ
        owner: *ref_1
        createdAt:
          type: string
          description: 作成日時
        scheduledEndTime:
          type: string
          description: 終了予定日時
        location:
          anyOf:
            - *ref_6
            - type: 'null'
          description: 位置情報
        city:
          type: string
          description: 市区町村
          nullable: true
        prefecture:
          type: string
          description: 都道府県
          nullable: true
      required:
        - id
        - theme
        - owner
        - createdAt
        - scheduledEndTime
    validationErrorItem:
      type: object
      properties:
        field:
          type: string
          faker: id
          description: バリデーションエラーのフィールド
        message:
          type: string
          description: バリデーションエラーメッセージ
      required:
        - field
        - message
    error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    user:
      type: object
      properties:
        displayID:
          type: string
          pattern: ^[A-Za-z0-9]$
          examples:
            - userid
          minLength: 3
          maxLength: 25
        displayName:
          type: string
        iconURL:
          type: string
          nullable: true
      required:
        - displayID
        - displayName
    opinion:
      type: object
      properties:
        id:
          type: string
          faker: '1'
          description: 意見ID
        title:
          type: string
        content:
          type: string
          description: 意見のテキスト
          minLength: 1
          maxLength: 140
        parentID:
          type: string
          description: 親の意見ID。ルートならば無し
        voteType: *ref_4
        pictureURL:
          type: string
          description: 画像が返る場合もある
        referenceURL:
          type: string
          description: 参考文献URL
      required:
        - content
        - id
    voteType:
      type: string
      description: 意見の3種のステータス
      enum:
        - agree
        - disagree
        - pass
        - unvote
      default: unvote
    location:
      type: object
      properties:
        latitude:
          type: number
          description: 緯度
        longitude:
          type: number
          description: 経度
      required:
        - latitude
        - longitude
    tokenClaim:
      type: object
      properties:
        aud:
          type: string
          description: Audience
        exp:
          type: string
          description: 有効期限
        iat:
          type: string
          description: 発行日時
        iss:
          type: string
          description: 発行者
        sub:
          type: string
          description: ユーザID
        jti:
          type: string
          description: JWT ID
        displayId:
          type: string
          description: ユーザーID
        displayName:
          type: string
          description: ユーザー名
        iconURL:
          type: string
          description: アイコンURL
        isVerify:
          type: boolean
          description: ユーザ登録済みか
      required:
        - aud
        - exp
        - iat
        - iss
        - sub
        - jti
        - isVerify
    offsetPagination:
      type: object
      properties:
        totalCount:
          type: integer
        offset:
          type: integer
        limit:
          type: integer
      required:
        - totalCount
        - offset
        - limit
    userDemographics:
      type: object
      properties:
        yearOfBirth:
          type: integer
          description: 誕生年
          nullable: true
        occupation:
          type: string
          title: 職業
          description: 職業
        gender:
          type: string
          title: 性別
          description: 性別
        city:
          type: string
          title: 市区町村
          description: 市区町村
          nullable: true
        householdSize:
          type: integer
          minimum: 1
          maximum: 5
          title: 世帯人数
          description: 世帯人数
          nullable: true
        prefecture:
          type: string
          description: 都道府県
          nullable: true
      required:
        - occupation
        - gender
    userGroupPosition:
      type: object
      properties:
        posX:
          type: number
        posY:
          type: number
        displayId:
          type: string
        displayName:
          type: string
        iconURL:
          type: string
          nullable: true
        groupName:
          type: string
        groupId:
          type: integer
        perimeterIndex:
          type: integer
          description: 境界ポイントのインデックス
      required:
        - posX
        - posY
        - displayId
        - groupName
        - displayName
        - groupId
    Report:
      type: object
      properties:
        talkSessionID:
          type: string
        content:
          type: string
          description: レポート本文
      required:
        - talkSessionID
        - content
  securitySchemes:
    apikey-header-SessionId:
      type: apiKey
      in: header
      name: SessionId
servers: []
